In [1]:
import pandas as pd
import numpy as np
import nltk

In [2]:
data_train=pd.read_csv("twitter-2013train-A.txt",sep='\t',header=None)

In [3]:
data_train.head()

0         1  \
0  264183816548130816  positive   
1  263405084770172928  negative   
2  262163168678248449  negative   
3  264249301910310912  negative   
4  262682041215234048   neutral   

                                                   2  
0  Gas by my house hit $3.39!!!! I\u2019m going t...  
1  Theo Walcott is still shit\u002c watch Rafa an...  
2  its not that I\u2019m a GSP fan\u002c i just h...  
3  Iranian general says Israel\u2019s Iron Dome c...  
4  Tehran\u002c Mon Amour: Obama Tried to Establi...

In [4]:
data_train.sample(20)

0         1  \
5917  101786196639883264  positive   
9211  251154711175106560  positive   
867   221444699322458115   neutral   
7298  101194901470986240   neutral   
6257  111326660908945408   neutral   
4068  264155923780612096   neutral   
4454  259397264504664064   neutral   
4998  246358852092694529   neutral   
5803  100230511959605248  positive   
1474  263074918260961280  positive   
5781  100076597658390528  positive   
6385  100017370185220096  positive   
608   264091046722560000   neutral   
8138  235616936795467777   neutral   
957   264131501376040961   neutral   
3657  262959496035459072   neutral   
557   251230219342602240   neutral   
1076  262254456400392192   neutral   
8212  259821602097737730  negative   
3054  256109715463995392   neutral   

                                                      2  
5917  Vampire Diaries and Jersey Shore tonight. So f...  
9211  @crazycharmx3 i love doing that\u002c hey we a...  
867   Today was National Kissing Day\u002c I\u2019ll...  
7298  @LaurenScottyXO oh there is no school today be...  
6257  @nidge1uk Yer off to take son for his first da...  
4068  @ArinRodriguez I texted you on Tuesday I was T...  
4454  Road Trip (sort of) with my boyfriend this Mon...  
4998  @ShutDownTheSun \""these birds dont buy the su...  
5803  @harryrippon10 yeah United were quality though...  
1474  Wish FIFA would make league results and tables...  
5781  RT @deltaupsilon: Boise State, Chattanooga, Em...  
6385  RT @CGBlasi: Very impressed with Joco Teenage ...  
608   My Thursday nights aren\u2019t the same with W...  
8138  @mahesha13 Ying wants to know if you still des...  
957   @CASS_TAR is addicted to ACT. She just took on...  
3657  Jennifer Aniston takes the plunge is low-cut\u...  
557   We\u2019re thinking of running on the Australi...  
1076  @BethFishReads Do you have chocolate? Sunday i...  
8212  @KelBel_x0 1st and 10\u002c ball on the WSH 34...  
3054  Photos: The 10th Hour & Fear of None played th...

In [5]:
data_train.columns=['id','sentiment','text']

In [6]:
data_test=pd.read_csv("twitter-2013test-A.txt",sep='\t',header=None)
data_test.columns=['id','sentiment','text']

In [7]:
data_dev=pd.read_csv("twitter-2013dev-A.txt",sep='\t',header=None)
data_dev.columns=['id','sentiment','text']


In [8]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Niang\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Niang\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [9]:
nltk.word_tokenize("bonjou comment vous allez")

['bonjou', 'comment', 'vous', 'allez']

# Stop words

In [10]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

# Stemming

In [11]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
input_str="There are several types of stemming algorithm."
input_str= nltk.word_tokenize(input_str)
for word in input_str :
    print(stemmer.stem(word))

there
are
sever
type
of
stem
algorithm
.


# Lemmatize

In [12]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
input_str="been had done languages cities nice "
input_str= nltk.word_tokenize(input_str)
for word in input_str :
    print(lemmatizer.lemmatize(word))

been
had
done
language
city
nice


In [13]:
import re

# Cette fonction regroupe les pretraitements du premier de mon corpus et sera généralisé dans l"emsemble du corpus par la fonction composition

In [14]:
def extraire_train(data):
        lemmatizer=WordNetLemmatizer()
        for index,row in data.iterrows():
            dictionnaire={}
            filter_sentence=[]
            i=1
            sentence=row['text']
            sentence = re.sub(r'[^\w\s]','',sentence)   #cleaning 
            words= nltk.word_tokenize(sentence)    # tokonization
            words =[w for w in words if not w in stop_words] #stopwords
            for word in words:
                filter_sentence.append(lemmatizer.lemmatize(word)) #lemmatizer
            #print(filter_sentence)
            for val in filter_sentence:
                    dictionnaire[val]=i
                    i+=1
            return dictionnaire

In [15]:
my_dict=extraire_train(data_train)

In [16]:
len(my_dict)

9

In [17]:
my_dict_test=extraire_train(data_test)

In [18]:
len(my_dict_test)

13

In [19]:
my_dict_dev=extraire_train(data_dev)

In [20]:
len(my_dict_dev)

12

In [21]:
from nltk import word_tokenize
from collections import Counter

In [22]:
def composition_train(data):
    ex=extraire_train(data)
    dictionnaire={}
    final_dictionnaire={}
    for item in range(0,(data.shape[0])):
        for i,val in ex.items():
            dictionnaire[i]=0
        for frequent in word_tokenize(data.iloc[item,-1]):
            if frequent in list(dictionnaire.keys()):
                dictionnaire[frequent]+=1
        if data.iloc[item,1]=='positive':
            dictionnaire['label']=2
        elif data.iloc[item,1]=='negative':
             dictionnaire['label']=1
        else:
            dictionnaire['label']=0
            
        final_dictionnaire[data.iloc[item,0]]=tuple(dictionnaire.values())
    matrice=np.array([final_dictionnaire[index] for index in final_dictionnaire.keys() ])
    return matrice

In [23]:
train=composition_train(data_train)

In [24]:
print(train)

[[1 1 1 ... 1 1 2]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]
 [0 0 0 ... 0 0 1]]


In [25]:
len(train)

9649

In [26]:
test=composition_train(data_test)
print(test)
print(len(test))

[[1 1 2 ... 1 1 2]
 [0 0 0 ... 0 0 2]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 1 2]
 [0 0 0 ... 0 0 0]]
3545


In [27]:
dev=composition_train(data_dev)
print(dev)
print(len(dev))

[[1 1 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
1649


In [28]:
file = open("train.svm", "w")
for i in range(train.shape[0]):
    file.write(str(train[i,-1]))
    file.write(' ')
    for j in range(train.shape[1]-1):
        file.write(str(j+1)+':'+str(train[i,j]))
        file.write(' ')
    file.write('\n')        
file.close()

In [29]:
file = open("test.svm", "w")
for i in range(test.shape[0]):
    file.write(str(test[i,-1]))
    file.write(' ')
    for j in range(test.shape[1]-1):
        file.write(str(j+1)+':'+str(test[i,j]))
        file.write(' ')
    file.write('\n')        
file.close()

In [30]:
file = open("dev.svm", "w")
for i in range(dev.shape[0]):
    file.write(str(train[i,-1]))
    file.write(' ')
    for j in range(dev.shape[1]-1):
        file.write(str(j+1)+':'+str(dev[i,j]))
        file.write(' ')
    file.write('\n')        
file.close()